### PR TITLE
Updated source to official ros repo

### PR DESCRIPTION
**Pull request by acxz**
and added patch to fix signal dependency until upstream releases new version

### CODE REVIEW

**Comment by acxz** [comment]
@bionade24 can you review my changes? I would like to continue trying to download and fix the ROS AUR packages for ros-melodic-desktop-full.

**Comment by bionade24** [comment]
I was always too lazy for writing a `.patch` file for this simple fix and just added a `sed` workaround. But this is even better than I did.
Edit: One small thing is missing: You forgot to update the `pkgrel` var, so that evryone gets the update.

**Comment by acxz** [comment]
np, wanted to learn how to patch anyway
Ah rip thx for spotting my mistake on pkgrel

**Comment by jwhendy** [comment]
Why do we need the patch now that the sources are updated to track ROS github? It's already there in upstream...

[geometry2/tf2/CMakeLists.txt](https://github.com/ros/geometry2/blob/melodic-devel/tf2/CMakeLists.txt#L6)
```
find_package(Boost REQUIRED COMPONENTS system thread)
```

[No `signals` in the list](https://github.com/ros/geometry2/pull/354).

**Comment by acxz** [comment]
This package is not a -git package so we take the latest release version, which does not have the signal fix.

**Comment by jwhendy** [comment]
Ahhh. Sorry about that. Man, that's surprising it's so behind. That fix was in Jan, it's almost June, and the last release was Nov 2018? That's a bummer, as I thought we'd be much more up to date with this migration to official sources :(

**Comment by bionade24** [comment]
This solved it only for 50% of the packages. The others still don't have a release, so I created some `-git` packages for the most important parts, that we can get the updates faster. I use the `-git` version, works well.

**Pull request merged**
